### ISSUE TITLE
Site down

### ISSUE THREAD

**Issue by zmmbreeze** [incompl/csslayoutsite#116]
Can't access http://zh.learnlayout.com/, please fix it. :smile:

**Comment by incompl** [comment]
Will fix today, sorry about that!

**Comment by leobalter** [comment]
Actually all the following subdomains are down:

- `zh`
- `zh-tw`
- `fa`
- `ko`
- `ja`
- `pt-pt`
- `pt-br`

**Comment by incompl** [comment]
I fixed the DNS configuration. Thanks for reporting this!

**Comment by zmmbreeze** [comment]
:+1:
