### ISSUE TITLE
IE11 bug with margin:auto centering

### ISSUE THREAD

**Issue by bfred-it** [incompl/csslayoutsite#117]
It looks like IE11 vertically stretches the children of display:flex elements, breaking [this centering method.](http://learnlayout.com/flexbox.html) 

![IE11 screenshot](https://cloud.githubusercontent.com/assets/1402241/6205236/759d48c4-b51c-11e4-9c07-64935d259657.png)

**Comment by incompl** [comment]
Fixed! Thanks for the bug report! I'll be deploying this change soon.

https://github.com/incompl/csslayoutsite/commit/0d0eeaf2a89fde997d800065ff977411d21f30cb
