### ISSUE TITLE
punctuation not visible

### ISSUE THREAD

**Issue by jedbt** [incompl/csslayoutsite#123]
CSS code samples don't show punctuation marks { : ; } on screen

**Comment by bdaley** [comment]
+1

Missing background color?

**Comment by jedbt** [comment]
Backgrounds off fixes it for print preview, still missing on screen

**Comment by leobalter** [comment]
It was an update on pygments breaking retrocompatibility.

After this is solved it is good to specify a pygments version or change it to a package version we can control.

**Comment by incompl** [comment]
I fixed the issue by rebuilding and redeploying the site with my current system.

I then updated my system from Pygments 1.6 to Pygments 2.0.2, _without_ merging the current PR for fixing this issue. This does not cause the site to build incorrectly. @leobalter, do you know what version of Pygments had the issue addressed in #124?

**Comment by leobalter** [comment]
I used Pygments 2.0.2. 

Maybe I am wrong this is related to pygments, but to other dependency.

I keep building it with the prefixed classes names.

**Comment by incompl** [comment]
Interesting. It must be another dependency. My Jekyll version is 2.0.3, what about yours?

**Comment by leobalter** [comment]
I'll need to confirm that tomorrow at the computer I used.

**Comment by leobalter** [comment]
I've found it => https://github.com/jekyll/jekyll/pull/2511 and https://github.com/jekyll/jekyll/releases/tag/v2.1.0

It was a breaking change on a minor version. :/

**Comment by incompl** [comment]
Fixed now, plus last-tested dependency versions added to README
