### ISSUE TITLE
#16 not working as intended

### ISSUE THREAD

**Issue by natrius** [incompl/csslayoutsite#141]
inline-block layout
The way you try it with 25% left and 75% right is not working. It is just possible when you lower one value for 1%, thats sometimes not as wanted.
And with this version it does not drop the right content below the navigation, but that was clear :)

Thanks for the site anyway.

**Comment by incompl** [comment]
Sounds like this may be due to whitespace between the elements in the HTML. Check this out for more info to see if that's what's happening: https://css-tricks.com/fighting-the-space-between-inline-block-elements/

**Comment by natrius** [comment]
Omg, i feel so silly. Thanks. Maybe you should mention it somewhere on the site.
Another suggestion - add the sourcecode just in a comment in HTML or something like that. 

At least now i will remember the whitespace between inline-block elements. Thanks :)

**Comment by incompl** [comment]
Yeah it's in a little bullet point on the site but it's really not explained that well. A comment in the source is a good idea.
