### ISSUE TITLE
CSS Grid

### ISSUE THREAD

**Issue by ylynfatt** [incompl/csslayoutsite#143]
I was wondering if there were any plans of adding a section on CSS Grid Layout?

https://gridbyexample.com/
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout

**Comment by incompl** [comment]
My plan is to no longer maintain the css framework list and eventually remove it.

**Comment by KaraAJC** [comment]
Also hoping to see the new Grid Layout model reflected, as flexbox is.
