### ISSUE TITLE
include toc as an off canvas menu

### ISSUE THREAD

**Issue by ghost** [incompl/csslayoutsite#146]
Hi, and first thanks for this site. I'd like to use the french version of the site with my high school students, and I'd like to add an off canvas navigation for easing the switch between pages. 
Would you like that I open a PR.

**Comment by incompl** [comment]
Sure, I'd be open to that PR. Would it be keyboard controlled with no UI?

**Comment by benjaminabel** [comment]
I thought it could be toggled with the current toc link button. Remove the TOC page and move it inside Jekyll includes.

**Comment by incompl** [comment]
I guess I'm not sure exactly what you're suggesting, maybe you could elaborate or mock something up?
