### ISSUE TITLE
suggestion: Add a PDF version

### ISSUE THREAD

**Issue by k-five** [incompl/csslayoutsite#148]
Hi. Please if you can, add a PDF version of the whole site.
The contents is worth it to be a simple/sweet ebook. 
I tried to create one, by copying it to Microsoft.word and then make a PDF of it, but  #result was ugly and messy.

Also if you had no time doing it yourself, give it to me (= the raw contents of the site) so I will try to create a  PDF of it.

thanks ::)

**Comment by incompl** [comment]
You're welcome to create a PDF version of the site. [I added a license to the readme to make it clear what is allowed](https://github.com/incompl/csslayoutsite/blob/master/README.textile#license), for example redistribution must be attributed and noncommercial.

**Comment by incompl** [comment]
The raw contents of the site are publicly available in this repo. It's probably not a format that makes it easy to convert to PDF but you're welcome to give it a go.
