### ISSUE TITLE
learnlayout.com domain expired

### ISSUE THREAD

**Issue by awongh** [incompl/csslayoutsite#154]
learnlayout.com domain expired since around yesterday.

**Comment by incompl** [comment]
Thanks for reporting this, the company who I bought my domains through got bought by another company and the new company apparently didn't automatically pay my invoices though autopay was set up and they had spammed me with a million emails about how they'd be paid through autopay but I guess they were not. I'm in the process of moving my domains to google domains, so I guess I'll buy a new one.

**Comment by incompl** [comment]
Hey good news, I talked to support and it turns out I do still own the domain. The site will be back up soon.

**Comment by incompl** [comment]
And it's back!
