### ISSUE TITLE
learnlayout.com is down

### ISSUE THREAD

**Issue by BoomAScopaz** [incompl/csslayoutsite#157]

**Comment by rrcobb** [comment]
it looks like incompl.com is down too - @incompl did you let something expire?

If hosting costs are a concern, please reach out! I have sent a ton of students here to learn, very worth it to me to get it back up!

**Comment by yuudi** [comment]
I just build a [backup](https://yuudi.github.io/csslayoutsite/en/) on github pages.

I think hosting on github pages is a good choice. You can merge my [**gh-pages** branch](https://github.com/yuudi/csslayoutsite/tree/gh-pages) to yours.

**Comment by incompl** [comment]
It's back up!
